Controllers/InstitutionsController.cs
using AvaliaAe.Models;
using AvaliaAe.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AvaliaAe.Controllers
{
    public class InstitutionsController : Controller
    {
        private readonly IInstitutionRepository _repository;
        public InstitutionsController(IInstitutionRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InsertNewInstitution()
        {
            return View();
        }

    }
}

Controllers/MyProfileController.cs
using AvaliaAe.Models;
using AvaliaAe.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AvaliaAe.Controllers
{
    public class MyProfileController : Controller
    {
        private readonly IUserRepository _repository;
        private readonly IInstitutionRepository _institutionRepository;

        public MyProfileController(IUserRepository repository, IInstitutionRepository institutionRepository)
        {
            _repository = repository;
            _institutionRepository = institutionRepository; 
        }

        public ActionResult Index() 
        {
      
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Profile(int id)
        {
            if (HttpContext.Session.GetString("type") != "user" || HttpContext.Session.GetString("type") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (HttpContext.Session.GetInt32("Id") != id)
            {
                return RedirectToAction("Index", "Login");
            }
			UserModel result = _repository.GetUser(id);
			return View(result);
        }

        public IActionResult InstitutionProfile(int id)
        {
            if (HttpContext.Session.GetString("type") != "inst" || HttpContext.Session.GetString("type") == null || HttpContext.Session.GetInt32("Id") != id)
            {
                return RedirectToAction("Index", "Home");
            }

         
            InstitutionModel inst = _institutionRepository.GetInstitutionById(id);
            if (inst == null) {
                return RedirectToAction("Index", "Home");
            }
     
            return View(inst);
        }
    }
}

Views/MyProfile/InstitutionProfile.cshtml
@model InstitutionModel

<div class="text-center">
    <h1 class="display-6 ">Meu perfil</h1>

</div>
@using (Html.BeginForm("", "", FormMethod.Post))
{
    <div class="container bg-light p-3">
        <div class="row">
            <div class="col text-center">
                <h3 class="display-6">Dados pessoais</h3>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="InstitutionName">
                    <label for="floatingInput">Nome</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Email">
                    <label for="floatingInput">Email</label>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Cnpj">
                    <label for="floatingInput">CNPJ</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Phone">
                    <label for="floatingInput">Número de telefone</label>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col text-center">
                <h3 class="display-6">Informações de localidade</h3>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Address">
                    <label for="floatingInput">Endereço</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="District">
                    <label for="floatingInput">Bairro</label>
                </div>
            </div>
        </div>

        <div class="row">
           
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Number">
                    <label for="floatingInput">Número</label>
                </div>
            </div>
        </div>

        <div class="row">
           
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="OwnerName">
                    <label for="floatingInput">Diretor da instituição</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="OwnerCpf">
                    <label for="floatingInput">CPF</label>
                </div>
            </div>
        </div>

       @* <div class="row">
            <div class="col text-center">
                <h3 class="display-6">Instituições associadas</h3>
            </div>
        </div>

       @* @if (true)
        {
            <div class="alert alert-secondary text-center">
                <h5>Ops... Parece que você não tem associação a nenhuma instituição...</h5>
                <div class="row">
                    <div class="col mt-3">
                        <button asp-controller="Institutions" asp-action="Index" class="btn btn-secondary">Achar minha instituição já!</button>

                    </div>
                </div>
            </div>
        }
        else
        {
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>mdo</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>fat</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td colspan="2">Larry the Bird</td>
                        <td>twitter</td>
                    </tr>
                </tbody>
            </table>*@
        @*}*@

    </div>

}

Views/MyProfile/Profile.cshtml
@model UserModel

<div class="text-center">
    <h1 class="display-6 ">Meu perfil</h1>
</div>
@using (Html.BeginForm("","", FormMethod.Post))
{
    <div class="container bg-light p-3">
        <div class="row">
            <div class="col text-center">
                <h3 class="display-6">Dados pessoais</h3>
            </div>
        </div>

            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Name"> 
                        <label for="floatingInput">Nome</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Email">
                        <label for="floatingInput">Email</label>
                    </div>
                </div>
               
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Cpf"> 
                        <label for="floatingInput">CPF</label>
                    </div>
                </div>
                 <div class="col">
                    <div class="form-floating mb-3">
                         <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Phone">
                         <label for="floatingInput">Número de telefone</label>
                    </div>
                 </div>
            </div>

            <div class="row">
                <div class="col text-center">
                    <h3 class="display-6">Informações de localidade</h3>
                </div>
            </div>

        <div class="row">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Address">
                    <label for="floatingInput">Endereço</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="District">
                    <label for="floatingInput">Bairro</label>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Cep">
                    <label for="floatingInput">CEP</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" disabled asp-for="Number">
                    <label for="floatingInput">Número</label>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col text-center">
                <h3 class="display-6">Instituições associadas</h3>
            </div>
        </div>

        @if (true)
        {
            <div class="alert alert-secondary text-center">
                <h5>Ops... Parece que você não tem associação a nenhuma instituição...</h5>
                <div class="row">
                    <div class="col mt-3">
                        <button asp-controller="Institutions" asp-action="Index" class="btn btn-secondary">Achar minha instituição já!</button>

                    </div>
                </div>
            </div>
        }
        else
        {
            <table class="table table-striped table-hover">
             <thead>
             <tr>
                 <th scope="col">#</th>
                 <th scope="col">First</th>
                 <th scope="col">Last</th>
                 <th scope="col">Handle</th>
             </tr>
             </thead>
            <tbody>
            <tr>
                <th scope="row">1</th>
                 <td>Mark</td>
                 <td>Otto</td>
                 <td>mdo</td>
            </tr>
                <tr>
                  <th scope="row">2</th>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>fat</td>
                </tr>
                <tr>
                  <th scope="row">3</th>
                  <td colspan="2">Larry the Bird</td>
                  <td>twitter</td>
                </tr>
              </tbody>
            </table>
        }

    </div>

}