Controllers/InstitutionsController.cs
using AvaliaAe.Models;
using AvaliaAe.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AvaliaAe.Controllers
{
    public class InstitutionsController : Controller
    {
        private readonly IInstitutionRepository _repository;
        public InstitutionsController(IInstitutionRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InsertNewInstitution()
        {
            return View();
        }

    }
}

Controllers/ToAssociateController.cs
using Microsoft.AspNetCore.Mvc;

namespace AvaliaAe.Controllers
{
    public class ToAssociateController : Controller
    {
        public IActionResult Index(int id)
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

    }
}

Views/Institutions/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <div class="text-center mt-5">
        <input type="text" class="form-control" placeholder="Digite o nome de uma instituição"/>
    </div>
    <div class="row mt-5">

    @foreach(int i in Enumerable.Range(1, 5))
    {
        <div class="col mb-3">
           <div class="card" style="width: 18rem;">
                    <img src="https://i.ytimg.com/vi/pegY6Uxg2UI/maxresdefault.jpg" class="card-img-top" alt="Institution image">
                 <div class="card-body">
                     <h5 class="card-title"><b>Nome da instuição</b></h5>
                        <p class="card-text"><i class="bi bi-geo-alt"></i> Localização</p>
                        <div class="row">
                            <div class="col mb-3">
                                @foreach (int star in Enumerable.Range(1, 5))
                                {
                                    <i class="bi bi-star-fill"></i>
                                }
                            </div>
                        </div>
                       <div class="text-center">
                            <a class="btn btn-primary" asp-controller="ToAssociate" asp-action="Index" asp-route-id=@i>Associar-se</a>

                       </div>
                 </div>
            </div>
        </div>
    }
    </div>

</div>

Views/Institutions/InsertNewInstitution.cshtml
<div class="text-center">
    <h3>Página em manutenção...</h3>
</div>